version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - cd hello-world
      - npm install
      - cd ..
  build:
    commands:
      - echo Packaging the SAM application...
      - sam build
  post_build:
    commands:
      - echo Deploying to AWS...
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name my-first-cloud-app --region ap-south-1 --capabilities CAPABILITY_IAM
artifacts:
  files:
    - template.yaml
    - hello-world/**/*