version: 0.2

env:
  variables:
    ImageName: "my-first-cloud-app"

phases:
  pre_build:
    commands:
      - echo "--- SYSTEM CHECK ---"
      - docker info || echo "Docker daemon is not running!"
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 549328952013.dkr.ecr.ap-south-1.amazonaws.com
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "--- CHECKING FILES ---"
      - ls -R
      - cd hello-world && npm install && cd ..
  build:
    commands:
      - echo "--- STARTING DOCKER BUILD ---"
      # This command prints the error specifically if it fails
      - docker build -t $ImageName:latest ./hello-world || { echo 'Docker build failed'; exit 1; }
  post_build:
    commands:
      - echo "--- DEPLOYING ---"
      - sam build --use-container
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name my-first-cloud-app --region ap-south-1 --capabilities CAPABILITY_IAM --image-repository 549328952013.dkr.ecr.ap-south-1.amazonaws.com/$ImageName