version: 0.2

env:
  variables:
    # 1. Define your image name here so the 'docker tag' command works
    ImageName: "my-first-cloud-app"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      # 2. This authenticates Docker with your AWS account
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 549328952013.dkr.ecr.ap-south-1.amazonaws.com
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - cd hello-world && npm install && cd ..
  build:
    commands:
      - echo Building Docker Image...
      # 3. This creates the image that was missing in your previous error
      - docker build -t $ImageName:latest .
      - echo Packaging the SAM application...
      - sam build --use-container
  post_build:
    commands:
      - echo Tagging and Pushing Image...
      - docker tag $ImageName:latest 549328952013.dkr.ecr.ap-south-1.amazonaws.com/$ImageName:latest
      - docker push 549328952013.dkr.ecr.ap-south-1.amazonaws.com/$ImageName:latest
      - echo Deploying to AWS...
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name my-first-cloud-app --region ap-south-1 --capabilities CAPABILITY_IAM --image-repository 549328952013.dkr.ecr.ap-south-1.amazonaws.com/$ImageName
artifacts:
  files:
    - template.yaml
    - hello-world/**/*